version: '2'
services:
  master:
    build: .
    environment:
      - WALE_WABS_PREFIX=
			- WABS_ACCOUNT_NAME=
			- WABS_ACCESS_KEY=
			- WABS_SAS_TOKEN=
    volumes:
      - ./data/master:/var/lib/postgresql/data
  slave:
    build: .
    environment:
      - WALE_WABS_PREFIX=
			- WABS_ACCOUNT_NAME=
			- WABS_ACCESS_KEY=
			- WABS_SAS_TOKEN=
      - POSTGRES_AUTHORITY=slave
    volumes:
      - ./data/slave:/var/lib/postgresql/data
